#![warn(missing_docs, clippy::dbg_macro, clippy::unimplemented)]
#![deny(
    rust_2018_idioms,
    future_incompatible,
    missing_debug_implementations,
    clippy::doc_markdown,
    clippy::default_trait_access,
    clippy::enum_glob_use,
    clippy::needless_borrow,
    clippy::large_digit_groups,
    clippy::explicit_into_iter_loop
)]

//! An example of the docs generated by mockiato.

use mockiato::mockable;

/// A cute little animal 🐷
#[mockable]
pub trait Animal {
    /// Makes a sound
    fn make_sound(&self);
}
