#![deny(missing_docs)]

//! An example of the docs generated by mockiato.

use mockiato::mockable;

/// A cute little animal 🐷
#[mockable]
pub trait Animal {
    /// Makes a sound
    fn make_sound(&self);
}
