//!
//! This module is used in the mocks generated by `mockiato-codegen`.
//! It may change at any time. Do not use this module directly.
//!

pub use self::arguments::*;
pub use self::expected_calls::*;
pub use self::fmt::*;
pub use self::matcher::*;
pub use self::method::*;
pub use self::method_call::*;
pub use self::return_value::*;

mod arguments;
mod expected_calls;
mod fmt;
mod matcher;
mod method;
mod method_call;
mod return_value;
