//!
//! This module is used in the mocks generated by `mockiato-codegen`.
//! It may change at any time. Do not use this module directly.
//!

pub use crate::arguments::Arguments;
pub use crate::fmt::MaybeDebugWrapper;
pub use crate::matcher::{ArgumentMatcher, ArgumentsMatcher};
pub use crate::method::Method;
pub use crate::method_call::MethodCallBuilder;
