//!
//! This module is used in the mocks generated by `mockiato-codegen`.
//! It may change at any time. Do not use this module directly.
//!

pub use self::arguments::Arguments;
pub use self::expected_calls::ExpectedCalls;
pub use self::fmt::{MaybeDebugExtWrapper, MaybeDebugWrapper};
pub use self::matcher::{ArgumentMatcher, ArgumentsMatcher};
pub use self::method::Method;
pub use self::method_call::MethodCallBuilder;

mod arguments;
mod expected_calls;
mod fmt;
pub(crate) mod matcher;
mod method;
mod method_call;
mod return_value;
